### ISSUE TITLE
Source code or how to compile these

### ISSUE THREAD

**Issue by varon** [mlc-ai/binary-mlc-llm-libs#2]
Thanks for making these available.

How can they be built manually? Can we include that in the README?

**Comment by tqchen** [comment]
Thanks for asking, they can be built via build.py  in https://github.com/mlc-ai/mlc-llm, we will be posting tutorials in the incoming weeks.

**Comment by yzh119** [comment]
Hi @varon , you can check our documentation on compile models: https://mlc.ai/mlc-llm/docs/tutorials/compile-models.html
