### ISSUE TITLE
[Request] Please generate Llama-2-7b-chat-hf-q4f16_1-cuda.dll

### ISSUE THREAD

**Issue by ParaN3xus** [mlc-ai/binary-mlc-llm-libs#39]
I want to use mlc-llm on windows with cuda. I have compiled mlc_chat_cli.exe with cuda enabled, but I still need this dll to run llama.

**Comment by thomascatlee** [comment]
mlc_chat_cli应该是没有后续支持了，看一下#89号issue的描述。

**Comment by ParaN3xus** [comment]
Thank you
