### ISSUE TITLE
Missing library files for Llama-2-70b-chat-hf-q4f16_1 model

### ISSUE THREAD

**Issue by lxrzlyr** [mlc-ai/binary-mlc-llm-libs#7]
I downloaded the 70b model and encountered an error when running it. The command I used was:

mlc_chat_cli --local-id Llama-2-70b-chat-hf-q4f16_1

I received the following error message:

WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Use MLC config: "/home/lxr/software/dist/prebuilt/mlc-chat-Llama-2-70b-chat-hf-q4f16_1/mlc-chat-config.json"
Use model weights: "/home/lxr/software/dist/prebuilt/mlc-chat-Llama-2-70b-chat-hf-q4f16_1/ndarray-cache.json"
Cannot find library "Llama-2-70b-chat-hf-q4f16_1-vulkan.so" in "dist/prebuilt/lib" or other search paths.

However, in the same directory, I have successfully deployed the 13b model. Could you please provide further guidance on how to resolve this issue?

**Comment by MasterJH5574** [comment]
Hi @lxrzlyr, we didn't provide the vulkan library for the 70b model since the amount of VRAM needed to run the 70b model will be over 50GB, which doesn't fit into a single consumer card usually.

**Comment by lxrzlyr** [comment]
Thank you for your response. I appreciate the clarification regarding the absence of the Vulkan library for the 70b model.
